name: Fetch Wiki

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: ~

jobs:
  Fetch-Wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python
        uses: astral-sh/setup-uv@v7

      - name: Install Dependencies
        run: |
          uv sync --all-extras --python=3.13

      - name: Fetch Remote Files
        run: |
          uv run main.py
          uv run fix_data.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v10
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          push: 'origin remote --force'
          new_branch: 'remote'
          message: ':sparkles: Fetch Wiki Changes'
          add: |
            'data'
