name: Fetch Wiki

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: ~

jobs:
  Fetch-Wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Fetch Remote Files
        run: |
          python main.py
          python fix_data.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          push: 'origin remote --force'
          new_branch: 'remote'
          message: ':sparkles: Fetch Wiki Changes'
          add: |
            'data'
